In [2]:
import pandas as pd

In [3]:
demo = pd.read_sas("data/DEMO_L.xpt")

In [4]:
# Check the dimensions of the Demographics dataset
print("Number of rows and columns:", demo.shape)

# Display all variable names
print(demo.columns.tolist())

Number of rows and columns: (11933, 27)
['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN', 'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'RIDEXAGM', 'DMQMILIZ', 'DMDBORN4', 'DMDYRUSR', 'DMDEDUC2', 'DMDMARTZ', 'RIDEXPRG', 'DMDHHSIZ', 'DMDHRGND', 'DMDHRAGZ', 'DMDHREDZ', 'DMDHRMAZ', 'DMDHSEDZ', 'WTINT2YR', 'WTMEC2YR', 'SDMVSTRA', 'SDMVPSU', 'INDFMPIR']

In [5]:
# Load the Weight History dataset
whq = pd.read_sas("data/WHQ_L.xpt")

# Check dimensions and variable names
print("Number of rows and columns:", whq.shape)
print(whq.columns.tolist())

Number of rows and columns: (8501, 5)
['SEQN', 'WHD010', 'WHD020', 'WHD050', 'WHQ070']

In [6]:
# Descriptive statistics for Weight History
whq.describe()

                SEQN       WHD010       WHD020       WHD050       WHQ070
count    8501.000000  8486.000000  8486.000000  8486.000000  8486.000000
mean   136369.136572   150.146712   317.142588   420.465237     1.548786
std      3443.283289   906.045672  1120.476550  1491.928102     0.520562
min    130378.000000    40.000000    63.000000    67.000000     1.000000
25%    133378.000000    63.000000   145.000000   145.000000     1.000000
50%    136402.000000    66.000000   174.000000   175.000000     2.000000
75%    139342.000000    70.000000   207.000000   214.000000     2.000000
max    142310.000000  9999.000000  9999.000000  9999.000000     9.000000

In [7]:
import numpy as np

# Make a copy of the original dataset
whq_clean = whq.copy()

# Replace special missing-value codes
whq_clean["WHD010"] = whq_clean["WHD010"].replace(
    [7777, 9999], np.nan
)

whq_clean["WHD020"] = whq_clean["WHD020"].replace(
    [7777, 9999], np.nan
)

whq_clean["WHD050"] = whq_clean["WHD050"].replace(
    [7777, 9999], np.nan
)

whq_clean["WHQ070"] = whq_clean["WHQ070"].replace(
    [7, 9], np.nan
)

# Examine descriptive statistics after cleaning
whq_clean.describe()

                SEQN       WHD010       WHD020       WHD050       WHQ070
count    8501.000000  8414.000000  8358.000000  8272.000000  8482.000000
mean   136369.136572    66.396601   179.502273   181.529014     1.545508
std      3443.283289     4.189235    48.115718    51.243241     0.497954
min    130378.000000    40.000000    63.000000    67.000000     1.000000
25%    133378.000000    63.000000   145.000000   145.000000     1.000000
50%    136402.000000    66.000000   173.000000   175.000000     2.000000
75%    139342.000000    69.000000   205.000000   210.000000     2.000000
max    142310.000000    83.000000   530.000000   530.000000     2.000000